#spring.data.mongodb.uri=mongodb://localhost:27017/practice

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=practice
server.port=5001
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.endpoint.health.show-details=always

#actuator shutdown endpoint
management.endpoint.shutdown.enabled=true

info.app.name = Spring Boot Inventory Services
info.app.description = Spring boot Restful Web Services
info.app.version = 1.0.0

spring.boot.message=Welcome to production Cloud 
